In [1]:
%matplotlib notebook
import pandas as pd

In [2]:
# Mapping lets you format an entire DataFrame
file = "Data/duke_energy_2010.csv"
file_df = pd.read_csv(file)
file_df.head()

,SAMPLE_ID,SAMPLE_ENERGY,SAMPLE_USAGE,SAMPLE_REVENUE,SAMPLE_HHAGE,SAMPLE_INC,SAMPLE_REGION,SAMPLE_ACCOUNT_ACTIVATION_DATE,SAMPLE_MAILING_ADDRESS,SAMPLE_MAILING_CITY,...,highenergyproblem,futurelifeconcern,ccreal,scarce,nuclear,solar,wind,muchasican,futurepower,phev
0,40414551,21156,1763.000000,3141.989990,6,7,SOUTH COASTAL,0,502 WHITE OAK DR,TARPON SPGS,...,10.0,9.0,10.0,10.0,10.0,10.0,10.0,7.0,9.0,9.0
1,40418276,3952,329.329987,586.179993,5,6,SOUTH COASTAL,0,10141 BRIAR CIR,HUDSON,...,10.0,10.0,10.0,9.0,1.0,10.0,10.0,9.0,5.0,4.0
2,40409966,19189,1599.079956,2664.229980,6,7,SOUTH CENTRAL,0,530 VISTA OAKS WAY,DAVENPORT,...,10.0,10.0,2.0,10.0,10.0,8.0,8.0,6.0,8.0,10.0
3,40410026,16647,1387.250000,2145.000000,5,6,SOUTH CENTRAL,0,2315 AVALON RD,SEBRING,...,9.0,9.0,1.0,6.0,9.0,9.0,7.0,4.0,4.0,5.0
4,30312281,10374,864.500000,1359.869995,7,3,SOUTH CENTRAL,0,3513 INDIAN SUMMER TRL,SEBRING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
list(file_df.columns)

['SAMPLE_ID',
 'SAMPLE_ENERGY',
 'SAMPLE_USAGE',
 'SAMPLE_REVENUE',
 'SAMPLE_HHAGE',
 'SAMPLE_INC',
 'SAMPLE_REGION',
 'SAMPLE_ACCOUNT_ACTIVATION_DATE',
 'SAMPLE_MAILING_ADDRESS',
 'SAMPLE_MAILING_CITY',
 'SAMPLE_MAILING_STATE',
 'SAMPLE_MAILING_ZIP',
 'SAMPLE_PRIMARY_PHONE',
 'SAMPLE_SECONDARY_PHONE',
 'SAMPLE_PREMISE_ADDRESS',
 'SAMPLE_PREMISE_CITY',
 'SAMPLE_PREMISE_STATE',
 'SAMPLE_PREMISE_ZIP',
 'SAMPLE_PREMISE_COUNTY',
 'SAMPLE_MONTHS',
 'SAMPLE_DWELLING',
 'SAMPLE_FAMCOMP',
 'SAMPLE_HHADULTS',
 'SAMPLE_HHCHILDS',
 'SAMPLE_HHPEOPLE',
 'SAMPLE_HOMEOWN',
 'SAMPLE_HISPANIC',
 'SAMPLE_ADDRYEAR',
 'SAMPLE_BALANCED_BILL',
 'SAMPLE_BANKDRAFT',
 'SAMPLE_CONSDISC',
 'SAMPLE_EBILL',
 'SAMPLE_EQUAL_PAY',
 'SAMPLE_HMW',
 'SAMPLE_SURGE',
 'SAMPLE_TOU',
 'SAMPLE_WATERHEATER',
 'SAMPLE_LOADCONTROL',
 'SAMPLE_AUDIT',
 'SAMPLE_CELL',
 'SAMPLE_VER_NUM',
 'SAMPLE_RDM_ID',
 'SAMPLE_RDM_',
 'SAMPLE_SRC_STRM',
 'SAMPLE_EFT',
 'SAMPLE_RES_AUDITS',
 'SAMPLE_BUDGETBILL',
 'SAMPLE_HMW_DELUX',
 'SAMPLE_DUCTREPAIR',
 'SAMPLE_INSULATION',
 'annkwh',
 'envprotection',
 'windpriority',
 'costpriority',
 'comfortpriority',
 'takensteps',
 'CFL',
 'hiwebuse',
 'acage',
 'heatage',
 'numberkids',
 'hhsize',
 'yearbuilt',
 'ccisreal',
 'protectfuture',
 'recycling',
 'redHHenergy',
 'allshouldconserve',
 'WEIGHT',
 'HICFL',
 'hisocnet',
 'facebook',
 'income',
 'lnkwh',
 'educ',
 '_est_restricted1',
 '_est_restricted2',
 'age',
 'yhat_p',
 'xbeta',
 'lambda',
 'yhat_nb',
 'xbetanb',
 'lambdanb',
 'male',
 'maleold',
 'maleold2',
 'probehavior',
 'climateworry',
 'futuregenimportant',
 'envprotveryimportant',
 'renewablesvimportant',
 'hisocnet2',
 'phat9',
 'educgradesch',
 'educsomehigh',
 'educhigh',
 'educsomecoll',
 'educcoll',
 'educpostgrad',
 'income20',
 'income49',
 'income75',
 'income100',
 'income150',
 'income150plus',
 'incomenonreport',
 'green',
 'numtvscomputers',
 'livingspace',
 'payattn',
 'considerproduct',
 'veryhotdays',
 'myright',
 'mycellphone',
 'firstone',
 'conscientiousrecycle',
 'reduceenergy',
 'realeffort',
 'willingchanges',
 'highenergyproblem',
 'futurelifeconcern',
 'ccreal',
 'scarce',
 'nuclear',
 'solar',
 'wind',
 'muchasican',
 'futurepower',
 'phev']

In [4]:
energy_subset=file_df[["SAMPLE_USAGE","SAMPLE_PREMISE_ZIP"]]

energy_subset_copy = energy_subset.copy()
energy_subset_copy["Zip"]=energy_subset["SAMPLE_PREMISE_ZIP"].astype(str)
energy_subset_copy.head(15)

    SAMPLE_USAGE  SAMPLE_PREMISE_ZIP        Zip
0    1763.000000               34689      34689
1     329.329987               34653      34653
2    1599.079956               33837      33837
3    1387.250000               33870      33870
4     864.500000               33872      33872
5     100.919998               33844      33844
6    1205.170044               34639      34639
7    1282.000000               33774      33774
8    1449.829956               33710      33710
9     523.669983               33761      33761
10   2261.919922           295502702  295502702
11   2725.250000               34639      34639
12   1661.829956               33761      33761
13    816.830017               33778      33778
14    142.080002               33542      33542

In [5]:
energy_subset_copy2 = energy_subset_copy.copy()

for row in range(0,len(energy_subset_copy["Zip"].astype(str))):
    if len(energy_subset_copy["Zip"].astype(str)) > 5:
       energy_subset_copy2["Zip"][row] = energy_subset_copy["Zip"][row][:5]
    else:
       energy_subset_copy2["Zip"][row] = energy_subset_copy["Zip"][row]

C:\Users\tmason\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [11]:
energy_subset_copy2.head(10000)

      SAMPLE_USAGE  SAMPLE_PREMISE_ZIP    Zip
0      1763.000000               34689  34689
1       329.329987               34653  34653
2      1599.079956               33837  33837
3      1387.250000               33870  33870
4       864.500000               33872  33872
5       100.919998               33844  33844
6      1205.170044               34639  34639
7      1282.000000               33774  33774
8      1449.829956               33710  33710
9       523.669983               33761  33761
10     2261.919922           295502702  29550
11     2725.250000               34639  34639
12     1661.829956               33761  33761
13      816.830017               33778  33778
14      142.080002               33542  33542
15     1125.000000               32792  32792
16     1372.420044               33703  33703
17     2182.830078               33765  33765
18      961.559998               34748  34748
19      541.250000               33710  33710
20     2138.750000               34683  34683
21     1088.420044           283793772  28379
22     1488.829956               33771  33771
23      432.500000           284053509  28405
24      794.080017           285125707  28512
25     1681.420044               33708  33708
26      672.330017               33756  33756
27      715.000000           283669034  28366
28     1083.500000           295015402  29501
29      271.920013           295747283  29574
...            ...                 ...    ...
4675   1273.829956           278568121  27856
4676   2602.199951               32713  32713
4677    344.420013               34432  34432
4678   1573.500000           284120954  28412
4679   1136.579956           285169702  28516
4680    999.500000           285403751  28540
4681   1296.670044               32810  32810
4682   1784.250000           276109269  27610
4683    421.079987           273068463  27306
4684   1451.920044               34786  34786
4685   1000.669983           283839603  28383
4686   1621.670044           275969767  27596
4687   1354.000000           287866833  28786
4688   1251.829956           295566761  29556
4689    944.830017           273798201  27379
4690   1820.329956               32828  32828
4691    483.250000               32837  32837
4692   1194.579956               32195  32195
4693    271.000000               34481  34481
4694   1501.920044           283141600  28314
4695   2213.669922               32708  32708
4696   1141.500000           284530000  28453
4697   1263.750000           295066813  29506
4698   1904.670044               32712  32712
4699    422.079987               32701  32701
4700   1563.750000           272036133  27203
4701   1217.829956           276152319  27615
4702    965.330017           276100000  27610
4703   1575.750000           295604259  29560
4704    518.830017           283068448  28306

[4705 rows x 3 columns]

In [12]:
file = "Data/us-zip-code-latitude-and-longitude.csv"
latlong_df = pd.read_csv(file,delimiter=';')
latlong_df.head()
latlong_df["Zip"]=latlong_df["Zip"].astype(str)

In [25]:
byzip = merged_df.groupby("Zip")
byzip_average = byzip["SAMPLE_USAGE"].mean()
byzip_average.head()

Zip
27203    1030.401063
27205    1604.375000
27207    1214.579956
27208     508.420013
27209    1726.415039
Name: SAMPLE_USAGE, dtype: float64

In [26]:
merged_df = pd.merge(byzip_average, latlong_df,
                                 how='inner', on='Zip')

In [27]:
merged_df.head(10000)

,Zip,SAMPLE_USAGE,City,State,Latitude,Longitude,Timezone,Daylight savings time flag,geopoint
0,27203,1030.401063,Asheboro,NC,35.686122,-79.829190,-5,1,"35.686122,-79.82919"
1,27205,1604.375000,Asheboro,NC,35.665973,-79.832161,-5,1,"35.665973,-79.832161"
2,27207,1214.579956,Bear Creek,NC,35.613837,-79.389840,-5,1,"35.613837,-79.38984"
3,27208,508.420013,Bennett,NC,35.559258,-79.545910,-5,1,"35.559258,-79.54591"
4,27209,1726.415039,Biscoe,NC,35.354158,-79.768390,-5,1,"35.354158,-79.76839"
5,27229,1081.500000,Candor,NC,35.280008,-79.794670,-5,1,"35.280008,-79.79467"
6,27298,1220.805994,Liberty,NC,35.884276,-79.568090,-5,1,"35.884276,-79.56809"
7,27305,341.250000,Milton,NC,36.532166,-79.213790,-5,1,"36.532166,-79.21379"
8,27306,659.191419,Mount Gilead,NC,35.227919,-79.997410,-5,1,"35.227919,-79.99741"
9,27312,1069.629567,Pittsboro,NC,35.756091,-79.178480,-5,1,"35.756091,-79.17848"
10,27314,1014.329987,Prospect Hill,NC,36.285009,-79.198090,-5,1,"36.285009,-79.19809"
11,27316,1408.415024,Ramseur,NC,35.711954,-79.637230,-5,1,"35.711954,-79.63723"
12,27317,761.776672,Randleman,NC,35.817411,-79.803890,-5,1,"35.817411,-79.80389"
13,27325,932.625031,Robbins,NC,35.447663,-79.575550,-5,1,"35.447663,-79.57555"
14,27330,1094.697823,Sanford,NC,35.458804,-79.164150,-5,1,"35.458804,-79.16415"
15,27332,1885.329956,Sanford,NC,35.401023,-79.144190,-5,1,"35.401023,-79.14419"
16,27341,1367.039978,Seagrove,NC,35.533320,-79.710180,-5,1,"35.53332,-79.71018"
17,27343,1520.957504,Semora,NC,36.495772,-79.093310,-5,1,"36.495772,-79.09331"
18,27344,883.629092,Siler City,NC,35.729692,-79.449840,-5,1,"35.729692,-79.44984"
19,27349,634.500000,Snow Camp,NC,35.897155,-79.423440,-5,1,"35.897155,-79.42344"
20,27355,1313.329956,Staley,NC,35.793860,-79.555210,-5,1,"35.79386,-79.55521"
21,27371,824.289993,Troy,NC,35.382213,-79.924180,-5,1,"35.382213,-79.92418"
22,27376,2089.479980,West End,NC,35.248989,-79.543830,-5,1,"35.248989,-79.54383"
23,27379,1426.460037,Yanceyville,NC,36.387904,-79.331070,-5,1,"36.387904,-79.33107"
24,27501,1295.943885,Angier,NC,35.494384,-78.710000,-5,1,"35.494384,-78.71"
25,27502,1128.979399,Apex,NC,35.736630,-78.864620,-5,1,"35.73663,-78.86462"
26,27503,895.790009,Bahama,NC,36.158344,-78.874190,-5,1,"36.158344,-78.87419"
27,27504,1232.473348,Benson,NC,35.390431,-78.531550,-5,1,"35.390431,-78.53155"
28,27505,1667.704956,Broadway,NC,35.426380,-79.034090,-5,1,"35.42638,-79.03409"
29,27506,2334.080078,Buies Creek,NC,35.406513,-78.738480,-5,1,"35.406513,-78.73848"
...,...,...,...,...,...,...,...,...,...
484,34668,1217.815231,Port Richey,FL,28.300730,-82.696980,-5,1,"28.30073,-82.69698"
485,34677,1638.750000,Oldsmar,FL,28.042799,-82.677370,-5,1,"28.042799,-82.67737"
486,34683,1399.977302,Palm Harbor,FL,28.076744,-82.761160,-5,1,"28.076744,-82.76116"
487,34684,1041.357501,Palm Harbor,FL,28.081325,-82.727510,-5,1,"28.081325,-82.72751"
488,34685,1164.482871,Palm Harbor,FL,28.099485,-82.695320,-5,1,"28.099485,-82.69532"
489,34688,1218.124992,Tarpon Springs,FL,27.891809,-82.724763,-5,1,"27.891809,-82.724763"
490,34689,1015.454444,Tarpon Springs,FL,28.149691,-82.753390,-5,1,"28.149691,-82.75339"
491,34690,908.665834,Holiday,FL,28.190181,-82.726960,-5,1,"28.190181,-82.72696"
492,34691,1097.096661,Holiday,FL,28.190060,-82.757350,-5,1,"28.19006,-82.75735"
493,34695,1220.500447,Safety Harbor,FL,28.005639,-82.695110,-5,1,"28.005639,-82.69511"
494,34698,1140.008653,Dunedin,FL,28.025395,-82.775340,-5,1,"28.025395,-82.77534"
495,34711,1216.503714,Clermont,FL,28.545742,-81.748050,-5,1,"28.545742,-81.74805"
496,34731,859.750020,Fruitland Park,FL,28.859765,-81.901840,-5,1,"28.859765,-81.90184"
497,34734,2222.783984,Gotha,FL,28.543429,-81.524790,-5,1,"28.543429,-81.52479"
498,34736,1350.636637,Groveland,FL,28.571677,-81.866490,-5,1,"28.571677,-81.86649"
499,34746,947.167511,Kissimmee,FL,28.287883,-81.468620,-5,1,"28.287883,-81.46862"
500,34747,1322.825020,Kissimmee,FL,28.326187,-81.588970,-5,1,"28.326187,-81.58897"
501,34748,1178.906012,Leesburg,FL,28.797245,-81.884660,-5,1,"28.797245,-81.88466"
502,34756,1882.000000,Montverde,FL,28.597126,-81.675790,-5,1,"28.597126,-81.67579"
503,34758,1110.470686,Kissimmee,FL,28.178192,-81.487310,-5,1,"28.178192,-81.48731"
504,34759,1171.590592,Kissimmee,FL,28.094144,-81.483950,-5,1,"28.094144,-81.48395"
505,34760,1487.329956,Oakland,FL,28.555328,-81.631040,-5,1,"28.555328,-81.63104"
506,34761,1258.132326,Ocoee,FL,28.574628,-81.529460,-5,1,"28.574628,-81.52946"
507,34762,692.669983,Okahumpka,FL,28.735088,-81.910350,-5,1,"28.735088,-81.91035"
508,34772,2752.419922,Saint Cloud,FL,28.198441,-81.272460,-5,1,"28.198441,-81.27246"
509,34785,1112.083313,Wildwood,FL,28.852564,-82.032100,-5,1,"28.852564,-82.0321"
510,34786,2031.085012,Windermere,FL,28.495982,-81.536200,-5,1,"28.495982,-81.5362"
511,34787,1361.269039,Winter Garden,FL,28.536794,-81.593440,-5,1,"28.536794,-81.59344"
512,34788,1292.103752,Leesburg,FL,28.857425,-81.784500,-5,1,"28.857425,-81.7845"
513,34797,2890.500000,Yalaha,FL,28.744182,-81.818590,-5,1,"28.744182,-81.81859"

In [28]:
import gmaps
import pandas as pd

# Google developer API key
from config import gkey

# Configure gmaps
gmaps.configure(api_key=gkey)

In [29]:
# Store latitude and longitude in locations
locations = merged_df[["Latitude", "Longitude"]]

# Fill NaN values and convert to float
usage = merged_df["SAMPLE_USAGE"].astype(float)

In [36]:
# Plot Heatmap


fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=usage, 
                                 dissipating=False, max_intensity=20000,
                                 point_radius=.25)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))